export declare const GUID: unique symbol;
export declare const PROXY: unique symbol;
export declare const GLOBAL_KEY: unique symbol;
export declare const PRIMITIVES: string[];
export declare const FAILED_SAVE = "failed in save file in ";
export declare const IS_ONLY_FOR_ROUTE = "is only for default route component directory";
export declare const SELF_CLOSE_TAGS: string[];
export declare const QUERY_ERROR = "The query selector for root element in index.html must be by id or tag name";
export declare const SERVING = "Serving at http://localhost:{0}\n\n";
export declare const COMMENTS = "\n\n/* ----- auto-generated code ----- */\n";
export declare const COLORS: {
    RESET: string;
    BRIGHT: string;
    DIM: string;
    UNDERSCORE: string;
    BLINK: string;
    REVERSE: string;
    HIDDEN: string;
    FG_BLACK: string;
    FG_RED: string;
    FG_GREEN: string;
    FG_YELLOW: string;
    FG_BLUE: string;
    FG_MAGENTA: string;
    FG_CYAN: string;
    FG_WHITE: string;
    FG_GRAY: string;
    BG_BLACK: string;
    BG_RED: string;
    BG_GREEN: string;
    BG_YELLOW: string;
    BG_BLUE: string;
    BG_MAGENTA: string;
    BG_CYAN: string;
    BG_WHITE: string;
    BG_GRAY: string;
};
export declare const STATUS_CODE: {
    CONTINUE: number;
    SWITCHING_PROTOCOLS: number;
    PROCESSING: number;
    EARLY_HINTS: number;
    OK: number;
    CREATED: number;
    ACCEPTED: number;
    NON_AUTHORITATIVE_INFORMATION: number;
    NO_CONTENT: number;
    RESET_CONTENT: number;
    PARTIAL_CONTENT: number;
    MULTI_STATUS: number;
    ALREADY_REPORTED: number;
    IM_USED: number;
    MULTIPLE_CHOICES: number;
    MOVED_PERMANENTLY: number;
    FOUND: number;
    SEE_OTHER: number;
    NOT_MODIFIED: number;
    USE_PROXY: number;
    TEMPORARY_REDIRECT: number;
    PERMANENT_REDIRECT: number;
    BAD_REQUEST: number;
    UNAUTHORIZED: number;
    PAYMENT_REQUIRED: number;
    FORBIDDEN: number;
    NOT_FOUND: number;
    METHOD_NOT_ALLOWED: number;
    NOT_ACCEPTABLE: number;
    PROXY_AUTHENTICATION_REQUIRED: number;
    REQUEST_TIMEOUT: number;
    CONFLICT: number;
    GONE: number;
    LENGTH_REQUIRED: number;
    PRECONDITION_FAILED: number;
    PAYLOAD_TOO_LARGE: number;
    URI_TOO_LONG: number;
    UNSUPPORTED_MEDIA_TYPE: number;
    RANGE_NOT_SATISFIABLE: number;
    EXPECTATION_FAILED: number;
    IM_A_TEAPOT: number;
    MISDIRECTED_REQUEST: number;
    UNPROCESSABLE_ENTITY: number;
    LOCKED: number;
    FAILED_DEPENDENCY: number;
    TOO_EARLY: number;
    UPGRADE_REQUIRED: number;
    PRECONDITION_REQUIRED: number;
    TOO_MANY_REQUESTS: number;
    REQUEST_HEADER_FIELDS_TOO_LARGE: number;
    UNAVAILABLE_FOR_LEGAL_REASONS: number;
    INTERNAL_SERVER_ERROR: number;
    NOT_IMPLEMENTED: number;
    BAD_GATEWAY: number;
    SERVICE_UNAVAILABLE: number;
    GATEWAY_TIMEOUT: number;
    HTTP_VERSION_NOT_SUPPORTED: number;
    VARIANT_ALSO_NEGOTIATES: number;
    INSUFFICIENT_STORAGE: number;
    LOOP_DETECTED: number;
    BANDWIDTH_LIMIT_EXCEEDED: number;
    NOT_EXTENDED: number;
    NETWORK_AUTHENTICATION_REQUIRED: number;
};
